Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EvrakTakipSistemi.Models.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Lütfen e-posta adresini boş geçmeyiniz.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Lütfen uygun formatta e-posta adresi giriniz.")]
        [Display(Name = "E-Posta ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Lütfen şifreyi boş geçmeyiniz.")]
        [DataType(DataType.Password, ErrorMessage = "Lütfen uygun formatta şifre giriniz.")]
        [Display(Name = "Şifre")]
        public string Password { get; set; }
        

        [Display(Name = "Beni Hatırla")]
        public bool Persistent { get; set; }

        public bool Lock { get; set; }
    }
}

Models/ViewModels/UpdatePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EvrakTakipSistemi.Models.ViewModels
{
    public class UpdatePasswordViewModel
    {
        [Display(Name = "Yeni Şifre")]
        [Required(ErrorMessage = "Lütfen şifreyi boş geçmeyiniz.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Controllers/RoleController.cs
using EvrakTakipSistemi.Models.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EvrakTakipSistemi.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EvrakTakipSistemi.Controllers
{
    [Authorize(Roles = "Admin,Moderator")]
    public class RoleController : Controller
    {
        Context c = new Context();
        readonly RoleManager<AppRole> _roleManager;
        readonly UserManager<AppUser> _userManager;
        public RoleController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // ROL ATAMA-YETKİ VERME
        public async Task<IActionResult> RoleAssign(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            List<AppRole> allRoles = _roleManager.Roles.ToList();
            List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>;
            List<RoleAssignViewModel> assignRoles = new List<RoleAssignViewModel>();
            allRoles.ForEach(role => assignRoles.Add(new RoleAssignViewModel
            {
                HasAssign = userRoles.Contains(role.Name),
                RoleId = role.Id,
                RoleName = role.Name
            }));

            return View(assignRoles);
        }
        [HttpPost]
        public async Task<ActionResult> RoleAssign(List<RoleAssignViewModel> modelList, string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);            

            foreach (RoleAssignViewModel role in modelList)
            {
                if (role.HasAssign)
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                else
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
            }

            //Yetkilendirme işleminden sonra kullanıcıya mail gönderme
            MailMessage msg = new MailMessage();
            msg.From = new MailAddress("destek@evraktakip.online", "Evrak Takip Sistemi", System.Text.Encoding.UTF8);
            msg.To.Add(user.Email);
            msg.Subject = "Bilgilendirme";
            msg.Body = "Sayın " + user.NameSurname + ",<br><br>" + " Gerekli erişim izinleri hesabınıza tanımlanmıştır. Eposta adresiniz ve şifreniz ile https://evraktakip.online bağlantısından sisteme giriş yapabilirsiniz." + "<br>" + "İyi çalışmalar dileriz..";
            msg.IsBodyHtml = true;

            using (SmtpClient client = new SmtpClient())
            {
                client.EnableSsl = true;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential("destek@evraktakip.online", "@Ysf.98783+");
                client.Host = "plsk21.servername.co";
                client.Port = 587;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;

                client.Send(msg);
            }

            return RedirectToAction("index", "user");
        }

        // ROL LİSTELEME
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        //ROL SİLME
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            AppRole role = await _roleManager.FindByIdAsync(id);
            
            if (role.Name=="Admin")// Admin rolü silinemez
            {
                TempData["ErrorMsg"] = "Admin rolü silinemez !";

                return RedirectToAction("index");
            }
            else
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    //Başarılı...
                }
                return RedirectToAction("index");
            }
        }

        // ROL EKLEME
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateRole(string id)
        {
            if (id != null)
            {
                AppRole role = await _roleManager.FindByIdAsync(id);

                return View(new RoleViewModel
                {
                    Name = role.Name
                });
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel model, string id)
        {
            IdentityResult result = null;
            if (id != null)
            {
                AppRole role = await _roleManager.FindByIdAsync(id);
                role.Name = model.Name;
                result = await _roleManager.UpdateAsync(role);
            }
            else
                result = await _roleManager.CreateAsync(new AppRole { Name = model.Name, OlusturulmaTarihi = DateTime.Now });

            if (result.Succeeded)
            {
                //Başarılı...
                return RedirectToAction("index");
            }
            else
            {
                return View();
            }
        }
    }
}

Controllers/UserController.cs
using ClosedXML.Excel;
using EvrakTakipSistemi.Models.Authentication;
using EvrakTakipSistemi.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;

namespace EvrakTakipSistemi.Controllers
{
    [Authorize(Roles = "Admin,Moderator")]
    public class UserController : Controller
    {
        readonly UserManager<AppUser> _userManager;
        readonly SignInManager<AppUser> _signInManager;
        readonly RoleManager<AppRole> _roleManager;

        public UserController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        //GİRİŞ İŞLEMİ
        [AllowAnonymous]
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await _userManager.FindByEmailAsync(model.Email);

                if (user != null)
                {
                    //İlgili kullanıcıya dair önceden oluşturulmuş bir Cookie varsa siliyoruz.
                    await _signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(user, model.Password, model.Persistent, model.Lock);

                    if (result.Succeeded)
                    {
                        await _userManager.ResetAccessFailedCountAsync(user); //Önceki hataları girişler neticesinde +1 arttırılmış tüm değerleri 0(sıfır)a çekiyoruz.

                        return RedirectToAction("warning", "home");
                    }
                    else
                    {
                        await _userManager.AccessFailedAsync(user); //Eğer ki başarısız bir account girişi söz konusu ise AccessFailedCount kolonundaki değer +1 arttırılacaktır. 

                        int failcount = await _userManager.GetAccessFailedCountAsync(user); //Kullanıcının yapmış olduğu başarısız giriş deneme adedini alıyoruz.
                        if (failcount == 3)
                        {
                            await _userManager.SetLockoutEndDateAsync(user, new DateTimeOffset(DateTime.Now.AddMinutes(1))); //Eğer ki başarısız giriş denemesi 3'ü bulduysa ilgili kullanıcının hesabını kilitliyoruz.
                            ModelState.AddModelError("Locked", "Art arda 3 başarısız giriş denemesi yaptığınızdan dolayı hesabınız 1 dk kitlenmiştir.");
                        }
                        else
                        {
                            if (result.IsLockedOut)
                                ModelState.AddModelError("Locked", "Art arda 3 başarısız giriş denemesi yaptığınızdan dolayı hesabınız 1 dk kilitlenmiştir.");
                            else
                                ModelState.AddModelError("NotUser2", "Hatalı şifre! Lütfen şifrenizi kontrol edin.");
                        }

                        TempData["ErrorMsg"] = "";
                        foreach (var items in ModelState.Values)
                        {
                            foreach (var er in items.Errors)
                            {

                                TempData["ErrorMsg"] = er.ErrorMessage.ToString() + TempData["ErrorMsg"].ToString();
                            }
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("NotUser", "Böyle bir kullanıcı bulunmamakta.");
                    TempData["ErrorMsg"] = "";
                    foreach (var items in ModelState.Values)
                    {
                        foreach (var er in items.Errors)
                        {

                            TempData["ErrorMsg"] = er.ErrorMessage.ToString() + TempData["ErrorMsg"].ToString();
                        }
                    }
                }
            }

            return View(model);
        }

        //ÇIKIŞ İŞLEMİ
        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

        //Kullanıcı Listeleme ve Arama
        public IActionResult Index(string id, string userName, string email, string NameSurname)
        {
            if (!string.IsNullOrEmpty(id))
            {
                return View(_userManager.Users.Where(x => x.Id.ToString().Contains(id) || id == null));
            }
            if (!string.IsNullOrEmpty(userName))
            {
                return View(_userManager.Users.Where(x => x.UserName.Contains(userName) || userName == null));
            }
            if (!string.IsNullOrEmpty(email))
            {
                return View(_userManager.Users.Where(x => x.Email.Contains(email) || email == null));
            }
            if (!string.IsNullOrEmpty(NameSurname))
            {
                return View(_userManager.Users.Where(x => x.NameSurname.Contains(NameSurname) || NameSurname == null));
            }
            return View(_userManager.Users);
        }

        // KAYIT İŞLEMİ
        [AllowAnonymous]
        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> SignIn(AppUserViewModel appUserViewModel)
        {
            if (ModelState.IsValid)
            {
                AppUser appUser = new AppUser
                {
                    UserName = appUserViewModel.UserName,
                    Email = appUserViewModel.Email,
                    NameSurname = appUserViewModel.NameSurname,
                    PhoneNumber = appUserViewModel.PhoneNumber,
                    Adress = appUserViewModel.Adress,

                };
                IdentityResult result = await _userManager.CreateAsync(appUser, appUserViewModel.Sifre);
                if (result.Succeeded)
                {
                    ModelState.Clear();

                    // Kayıt tamamlandıktan sonra sistem epostasına bilgilendirici mail gönderme
                    MailMessage msg = new MailMessage();
                    msg.From = new MailAddress("destek@evraktakip.online", "Evrak Takip Sistemi", System.Text.Encoding.UTF8);
                    msg.To.Add("destek@evraktakip.online");
                    msg.Subject = "Yeni Kayıt";
                    msg.Body = "Kullanıcı Adı: " + appUser.UserName + "<br><br>" + "Eposta: " + appUser.Email + "<br><br> Lütfen gerekli incelemeleri yaptıktan sonra uygun yetkileri veriniz..";
                    msg.IsBodyHtml = true;

                    using (SmtpClient client = new SmtpClient())
                    {
                        client.EnableSsl = true;
                        client.UseDefaultCredentials = false;
                        client.Credentials = new NetworkCredential("destek@evraktakip.online", "@Ysf.98783+");
                        client.Host = "plsk21.servername.co";
                        client.Port = 587;
                        client.DeliveryMethod = SmtpDeliveryMethod.Network;

                        client.Send(msg);
                    }
                    ViewBag.State = true;
                }
                else
                    result.Errors.ToList().ForEach(e => ModelState.AddModelError(e.Code, e.Description));

            }
            return View();
        }

        // PERSONEL BİLGİ GETİRME
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var model = new AppUserViewModel
            {
                UserName = user.UserName,
                NameSurname = user.NameSurname,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                Adress = user.Adress,
            };
            return View(model);
        }

        // PERSONEL BİLGİ GÜNCELLEME
        [HttpPost]
        public async Task<IActionResult> EditUser(AppUserViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.Id.ToString());

            user.UserName = model.UserName;
            user.NameSurname = model.NameSurname;
            user.Email = model.Email;
            user.PhoneNumber = model.PhoneNumber;
            user.Adress = model.Adress;

            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(model);
        }

        //PERSONEL KAYIT SİLME
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>; //Seçilen personelin rollerini listeliyoruz.

            if (userRoles.Contains("Admin")) //Eger userRoles listesinde Admin değeri varsa.
            {
                TempData["ErrorMsg"] = "Admin yetkisi olan kullanıcı silinemez !";

                return RedirectToAction("index");
            }
            else
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {

Views/User/EditUser.cshtml
@model EvrakTakipSistemi.Models.ViewModels.AppUserViewModel
@{
    ViewData["Title"] = "IncomingDocGet";
    Layout = Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <title>Bilgi Güncelle</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="text-align:center;">Bilgi Düzenle</h4>
                    </div>
                    <div class="modal-body">

                        @using (Html.BeginForm())
                        {
                            <b>Personel Id:</b>
                            @Html.TextBoxFor(x => x.Id, new { @readonly = true, @class = "form-control" })

                            <b>Ad Soyad:</b><br />
                            @Html.ValidationMessageFor(model => model.NameSurname, "", new { @style = "color:red" })
                            @Html.TextBoxFor(x => x.NameSurname, new { @class = "form-control" })

                            <b>Kullanıcı Adı:</b><br />
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @style = "color:red" })
                            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })

                            <b>E-Posta:</b><br />
                            @Html.ValidationMessageFor(model => model.Email, "", new { @style = "color:red" })
                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })

                            <b>Telefon Numarası:</b><br />
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @style = "color:red" })
                            @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })

                            <b>Adres:</b><br />
                            @Html.ValidationMessageFor(model => model.Adress, "", new { @style = "color:red" })
                            @Html.TextBoxFor(x => x.Adress, new { @class = "form-control" })

                            <div class="modal-footer">
                                <button class="btn btn-primary">Güncelle</button>
                                <a href="/user/index" class="btn btn-danger">İptal</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    $(function () {
        $('#myModal').modal({ backdrop: 'static', keyboard: false, show: true });
    });
</script>

Views/User/Index.cshtml
@model IEnumerable<EvrakTakipSistemi.Models.Authentication.AppUser>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<title>Personel Listesi</title>
<link href="~/AdminPanel/css/SearchFilter.css" rel="stylesheet" />
<body>
    @* LİSTE FİLTRELEME *@
    <div class="searchArea">
        <div class="search">
            @using (Html.BeginForm())
            {
                <div>
                    @Html.TextBox("id", null, new { @class = "form-control-search", @placeholder = "Personel Id ile Ara" })
                </div>
            }
        </div>
        <div class="search">
            @using (Html.BeginForm())
            {
                <div>
                    @Html.TextBox("userName", null, new { @class = "form-control-search", @placeholder = "Kullanıcı Adı ile Ara" })
                </div>
            }
        </div>
        <div class="search">
            @using (Html.BeginForm())
            {
                <div>
                    @Html.TextBox("NameSurname", null, new { @class = "form-control-search", @placeholder = "Ad Soyad ile Ara" })
                </div>
            }
        </div>
        <div class="search">
            @using (Html.BeginForm())
            {
                <div>
                    @Html.TextBox("email", null, new { @class = "form-control-search", @placeholder = "Eposta ile Ara" })
                </div>
            }
        </div>
        <div>
            <button class="clean-filter" onclick="document.location='/user/index'">Filtreyi Temizle</button>
        </div>
    </div>

    @* --KULLANICI TABLOSU-- *@
    <div class="content">
        <a style="float:left; font-size:inherit; color:#36b9bf;" href="/user/exportexcel">▹Listeyi İndir</a>
        <div style="color:red; margin-right:10px; text-align:right;">@TempData["ErrorMsg"]</div>
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Personel ID</th>
                    <th>Kullanıcı Adı</th>
                    <th>Ad / Soyad</th>
                    <th>Adres</th>
                    <th>Eposta</th>
                    <th>Telefon</th>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr class="odd gradeX">
                        <td>@x.Id</td>
                        <td>@x.UserName</td>
                        <td>@x.NameSurname</td>
                        <td>@x.Adress</td>
                        <td>@x.Email</td>
                        <td>@x.PhoneNumber</td>
                        <td><a asp-action="RoleAssign" asp-controller="Role" asp-route-id="@x.Id" class="btn btn-warning">Yetki Düzenle</a></td>
                        <td>@Html.ActionLink("Düzenle", "EditUser", new { id = x.Id }, new { @class = "btn btn-primary"})</td>
                        <td>@Html.ActionLink("Sil", "DeleteUser", new { id = x.Id }, new { @class = "btn btn-danger", onclick = "return confirm('U Y A R I   |   Kayıt silinmek üzere..');" })</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>   
</body>

Views/User/Login.cshtml
@model EvrakTakipSistemi.Models.ViewModels.LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html lang="zxx">

<head>
    <title>Evrak Takip Sistemi</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <link href="~/Login/Login.css" rel="stylesheet" />
</head>
<body>
    <h1 class="h1">EVRAK TAKİP SİSTEMİ</h1><br /><br /><br />
    <div class="container" id="container">
        <!--Personel Giriş Formu-->
        <div class="form-container sign-in-container">
            @using (Html.BeginForm("Login", "User", FormMethod.Post))
            {
                <h1>Personel Girişi</h1><br /><br />

                @Html.ValidationMessageFor(model => model.Email, "", new { @style = "color:red" })
                <input type="email" placeholder="Eposta.." name="Email" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @style = "color:red" })
                <input type="password" placeholder="Şifre.." name="Password" /><br />
                <button>Giriş Yap</button>
                <a href="/user/passwordreset">Şifremi Unuttum</a><br /><br />
                <label>veya</label><br />
                <a href="/User/SignIn">Kayıt Ol</a>
            }
        </div>
        <!--Yönetici Giriş Formu-->
        <div class="form-container sign-up-container">
            @using (Html.BeginForm("Login", "Admin", FormMethod.Post))
            {
                <h1>Yönetici Girişi</h1><br /><br />

                @Html.ValidationMessageFor(model => model.Email, "", new { @style = "color:red" })
                <input type="email" placeholder="Eposta.." name="Email" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @style = "color:red" })
                <input type="password" placeholder="Şifre.." name="Password" /><br />
                <button>Giriş Yap</button>
                <a href="/user/passwordreset">Şifremi Unuttum</a><br /><br />
                <label>veya</label><br />
                <a href="/User/SignIn">Kayıt Ol</a>
            }
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Merhaba,</h1>
                    <p>
                        Evrak kayıt sistemine hoş geldiniz. Sistemde yapılacak olan tüm işlemlerden hesap sahibi sorumludur.
                        Hesabınızla ilgili bir problem olduğunu düşünüyorsanız lütfen bizimle iletişime geçin.
                    </p>
                    <p><a style="color:#c1c1c1;" href="/user/UserAgreement">Kullanıcı Sözleşmesi</a></p><br />
                    <p>İyi çalışmalar dileriz..</p>
                    <button class="ghost" id="signIn">~ Personel Girişi ~</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Merhaba,</h1>
                    <p>
                        Evrak kayıt sistemine hoş geldiniz. <br />Lütfen hesap bilgilerinizi başkalarıyla paylaşmayın.
                        Hesabınızla ilgili bir problem olduğunu düşünüyorsanız lütfen bizimle iletişime geçin.
                    </p>
                    <p><a  style="color:#c1c1c1;" href="/user/UserAgreement">Kullanıcı Sözleşmesi</a></p><br />
                    <p>İyi çalışmalar dileriz..</p>
                    <button class="ghost" id="signUp">~ Yönetici Girişi ~</button>
                </div>
            </div>
        </div>
    </div>

    <!--HATA MESAJLARI -->
    <div id="divPartial">
        @if (TempData["ErrorMsg"] != null)
        {
            <p style="color:red;" class="alert alert-warning" role="alert">@TempData["ErrorMsg"] <br /></p>
        }
    </div>
    <script src="~/Login/Login.js"></script>
</body>
</html>

Views/User/PasswordReset.cshtml
@model EvrakTakipSistemi.Models.ViewModels.ResetPasswordViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Şifre Yenile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="text-align:center;">YENİ ŞİFRE TALEP</h4>
                    </div>
                    <div class="modal-body">

                        @if (ViewBag.State == null)
                        {
                            @using (Html.BeginForm())
                            {
                                <label>Eposta:</label>
                                @Html.TextBoxFor(x => x.Email, new { @placeholder = "E-posta..", @class = "form-control" })

                                <div class="modal-footer">
                                    <button class="btn btn-primary" type="submit">Şifre Talep Et</button>
                                    <a href="/user/login" class="btn btn-danger">İptal</a>
                                </div>
                            }
                        }
                        else
                        {
                            if (ViewBag.State)
                            {
                                @:<div class="alert-info">Şifre talebi için e-posta adresinize bilgilerindirici mail gönderilmiştir.</div><br />
                                <div class="modal-footer">
                                    <a href="/user/login" class="btn btn-primary">Giriş Yap</a>
                                </div>

                            }
                            else
                            {
                                @:<div class="alert-warning">Böyle bir e-posta bulunmamaktadır.</div><br />
                                <div class="modal-footer">
                                    <a href="/user/passwordreset" class="btn btn-primary">Yeni Şifre Talep Et</a>
                                    <a href="/user/login" class="btn btn-danger">İptal</a>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    $(function () {
        $('#myModal').modal({ backdrop: 'static', keyboard: false, show: true });
    });
</script>